meta:
  name: Training Calendar
  version: 1.0.0
  created_at: "2025-09-20T13:12:53.750886"
fields:
  - field: week
    type: string
  - field: course
    type: string
  - field: trainer
    type: string
  - field: room
    type: string
