meta:
  name: Training Budget
  version: 1.0.0
  created_at: "2025-09-20T13:12:53.749486"
fields:
  - field: category
    type: string
  - field: amount
    type: number
  - field: justification
    type: string
