meta:
  name: WiFi Enterprise Config
  version: 1.0.0
  created_at: "2025-09-20T13:28:29.310235"
fields:
  - field: ssid
    type: string
  - field: vlan
    type: string
  - field: auth
    type: string
